server:
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  data:
    mongodb:
      uri: mongodb://localhost:27017/restaurant
stripe:
  webhook:
    secret:
      key: whsec_fb8a927989f80960bb5455a68cab13ef5b31bc9d1ed5e631ae2c684edb4055e6
  secret:
    key: sk_test_51QcNR7BX63RHM1QOLw4knOIBiZmeRE0wpLcuYeEiiqzulZXd0d4O7R7xJiUyfdLCL5LvKtvzD2d7BrCOpDnHT8GL00Qpa787RX
